#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

umask 077
ENV_FILE="${TMPDIR:-/tmp}/migmate-archive-prereqs.env"

# load_env KEY... reads each KEY out of ENV_FILE without evaluating the file.
# The file-route wizard sources its env file; this one must not, because the
# archive route is the first to collect operator-typed values that are not
# GUIDs or paths, and a sourced file executes whatever they contain.
load_env() {
  local key value
  for key in "$@"; do
    value=$(_existing "$key" || true)
    printf -v "$key" '%s' "$value"
  done
}

# decode_component percent-decodes one URL path segment, which is how the
# Teams "Get link to channel" URL carries a channel id.
decode_component() {
  printf '%b' "${1//%/\\x}"
}

RESUME=0
if [[ "${1:-}" == "--resume" ]]; then
  RESUME=1
  ENV_FILE="${2:-}"
  if [[ ! -f "$ENV_FILE" ]]; then
    warn "usage: ${0##*/} --resume /path/to/.archive-prereqs.env"
    exit 1
  fi
  load_env MIGMATE_PREREQ_DIR
  if [[ -z "$MIGMATE_PREREQ_DIR" ]]; then
    warn "the env file must record MIGMATE_PREREQ_DIR"
    exit 1
  fi
  PREREQ_DIR="$MIGMATE_PREREQ_DIR"
  _STAGE_INDEX=5
fi

if (( ! RESUME )); then

banner "Migmate Teams-archive prerequisites"

stage "Prerequisite directory and tenant"
say "These prerequisites live beside the file route's, in one operator-owned directory outside the repository."
say "Nothing secret is ever written into the repo, into a job folder, or into this script's output."
DEFAULT_PREREQ_DIR="$HOME/.config/migmate"
say "The file route's wizard usually writes to $DEFAULT_PREREQ_DIR."
ask MIGMATE_PREREQ_DIR "Operator-owned absolute directory for these prerequisite files:"
if [[ -z "$MIGMATE_PREREQ_DIR" ]]; then MIGMATE_PREREQ_DIR="$DEFAULT_PREREQ_DIR"; fi
case "$MIGMATE_PREREQ_DIR" in
  /*) ;;
  *) warn "the directory must be an absolute path"; exit 1 ;;
esac
case "$MIGMATE_PREREQ_DIR" in
  "$PWD"|"$PWD"/*) warn "keep prerequisites outside the repository"; exit 1 ;;
esac
PREREQ_DIR="$MIGMATE_PREREQ_DIR"
mkdir -p "$PREREQ_DIR/entra"
# Move the env file into the prerequisite directory before anything is stored.
OLD_ENV_FILE="$ENV_FILE"
ENV_FILE="$PREREQ_DIR/.archive-prereqs.env"
if [[ -f "$OLD_ENV_FILE" && ! -f "$ENV_FILE" ]]; then cp "$OLD_ENV_FILE" "$ENV_FILE"; fi
write_env MIGMATE_PREREQ_DIR "$PREREQ_DIR"
write_env MIGMATE_PREREQ_ENV_FILE "$ENV_FILE"

# The tenant is the same one the file route already uses, so offer that value.
FILE_ROUTE_ENV="$PREREQ_DIR/.stage1-prereqs.env"
if [[ -f "$FILE_ROUTE_ENV" ]] && [[ -z "$(_existing MIGMATE_TENANT_ID || true)" ]]; then
  INHERITED_TENANT=$(grep -E '^MIGMATE_TENANT_ID=' "$FILE_ROUTE_ENV" | tail -n1 || true)
  if [[ -n "$INHERITED_TENANT" ]]; then
    write_env MIGMATE_TENANT_ID "${INHERITED_TENANT#*=}"
    note "inherited the tenant id from the file route's prerequisites"
  fi
fi
ask MIGMATE_TENANT_ID "Paste the Directory (tenant) ID:"
write_env MIGMATE_TENANT_ID "$MIGMATE_TENANT_ID"
write_env MIGMATE_ENTRA_TENANT_ID_FILE "$PREREQ_DIR/entra/tenant-id.txt"
printf '%s' "$MIGMATE_TENANT_ID" > "$PREREQ_DIR/entra/tenant-id.txt"
chmod 600 "$PREREQ_DIR/entra/tenant-id.txt"
pause

stage "Archive Entra app registration"
say "The archive route needs its own app registration. It cannot share the file route's app or its fixture mutator."
note "src/engine/providers/credentials.ts applies ARCHIVE_ROLES as an exclusive allowlist: a token carrying any"
note "role outside it — Sites.Selected included — refuses with credential_permissions_invalid. An app that can"
note "write to SharePoint must not also be the identity that reads every Teams message in the tenant."
if confirm "Register the archive app and create its client secret now?"; then
  open_url "https://entra.microsoft.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade"
  step "New registration, single tenant, name it something like 'Migmate archive'. No redirect URI is needed."
  step "API permissions → Add a permission → Microsoft Graph → Application permissions."
  step "Add exactly these three, and nothing else:"
  note "    Channel.ReadBasic.All      resolves a channel through /teams/{teamId}/channels"
  note "    ChannelMessage.Read.All    the channel export route"
  note "    Chat.Read.All              the user-chats export route"
  warn "Do not add Files.Read.All, OnlineMeetingTranscript.Read.All or OnlineMeetings.Read.All yet."
  note "Those belong to the attachmentBytes and transcripts options, which this first qualification leaves off."
  step "Grant admin consent from the API permissions blade. There is no /adminconsent URL for a client-credentials app with no redirect URI."
  step "Certificates & secrets → New client secret → copy the Value, not the Secret ID."
  pause "Press Enter once the app exists, the three permissions are consented, and you have the secret value."
fi
ask MIGMATE_ARCHIVE_CLIENT_ID "Paste the archive app's Application (client) ID:"
FILE_ROUTE_CLIENT=$(grep -E '^MIGMATE_CLIENT_ID=|^MIGMATE_PROBE_MUTATOR_CLIENT_ID=' "$FILE_ROUTE_ENV" 2>/dev/null | cut -d= -f2- || true)
for existing in $FILE_ROUTE_CLIENT; do
  if [[ "$MIGMATE_ARCHIVE_CLIENT_ID" == "$existing" ]]; then
    warn "that is one of the file route's apps; its Sites.Selected role refuses the archive credential"
    exit 1
  fi
done
write_env MIGMATE_ARCHIVE_CLIENT_ID "$MIGMATE_ARCHIVE_CLIENT_ID"
write_env MIGMATE_ARCHIVE_CLIENT_ID_FILE "$PREREQ_DIR/entra/archive-client-id.txt"
printf '%s' "$MIGMATE_ARCHIVE_CLIENT_ID" > "$PREREQ_DIR/entra/archive-client-id.txt"
chmod 600 "$PREREQ_DIR/entra/archive-client-id.txt"
pause

stage "Disposable archive scope and its in-scope samples"
say "The qualification suite reads real conversations. It refuses to run without real samples in them, and"
say "it refuses any collection gap, so point it at content you created for this purpose."
warn "A channel scope reads the whole team. Graph v1.0 has no per-channel export route: the collector calls"
warn "/teams/{teamId}/channels/getAllMessages and discards what the scope did not name. Every channel in that"
warn "team crosses the network, so use a team that exists only for this."
say ""
say "In a throwaway team, with no channels beyond the automatic General:"
step "Post a message in General whose body contains a pasted image."
step "Reply inside that post, and paste an image into the reply too. Both samples are required separately."
step "With a dedicated test user, hold one 1:1 chat containing a message with a pasted image."
note "Team creation and member additions add system event messages with no sender. Those are expected:"
note "they become identity_unresolved findings, which the suite admits."
pause "Press Enter once that content exists."
say ""
say "In Teams, right-click the General channel → Get link to channel, and paste the whole URL."
ask MIGMATE_ARCHIVE_CHANNEL_LINK "Paste the channel link (or leave empty to enter ids by hand):"
if [[ -n "$MIGMATE_ARCHIVE_CHANNEL_LINK" ]]; then
  ENCODED_CHANNEL="${MIGMATE_ARCHIVE_CHANNEL_LINK#*/l/channel/}"
  ENCODED_CHANNEL="${ENCODED_CHANNEL%%/*}"
  MIGMATE_ARCHIVE_CHANNEL_ID=$(decode_component "$ENCODED_CHANNEL")
  GROUP_QUERY="${MIGMATE_ARCHIVE_CHANNEL_LINK#*groupId=}"
  MIGMATE_ARCHIVE_TEAM_ID="${GROUP_QUERY%%&*}"
  if [[ "$MIGMATE_ARCHIVE_CHANNEL_ID" != 19:* || -z "$MIGMATE_ARCHIVE_TEAM_ID" ]]; then
    warn "that does not look like a channel link; expected .../l/channel/19%3A...%40thread.tacv2/...?groupId=<guid>"
    exit 1
  fi
  write_env MIGMATE_ARCHIVE_CHANNEL_LINK "$MIGMATE_ARCHIVE_CHANNEL_LINK"
  note "team id:    $MIGMATE_ARCHIVE_TEAM_ID"
  note "channel id: $MIGMATE_ARCHIVE_CHANNEL_ID"
else
  ask MIGMATE_ARCHIVE_TEAM_ID "Paste the team id (the link's groupId):"
  ask MIGMATE_ARCHIVE_CHANNEL_ID "Paste the channel id (19:...@thread.tacv2):"
fi
write_env MIGMATE_ARCHIVE_TEAM_ID "$MIGMATE_ARCHIVE_TEAM_ID"
write_env MIGMATE_ARCHIVE_CHANNEL_ID "$MIGMATE_ARCHIVE_CHANNEL_ID"
say ""
say "The user-chats scope entry names a user by object id, and covers every chat that user is in."
note "Find it with GET /v1.0/users/<upn> in Graph Explorer, or read it off the chat's members."
ask MIGMATE_ARCHIVE_USER_ID "Paste the test user's object id:"
write_env MIGMATE_ARCHIVE_USER_ID "$MIGMATE_ARCHIVE_USER_ID"
pause

stage "Collection window and display timezone"
say "The window is a closed half-open UTC modification window: a record counts when its lastModifiedDateTime"
say "is at or after 'from' and strictly before 'to'. It is a modification window, not a creation window."
note "The export routes accept only a strictly-greater lower bound, so the request asks for one millisecond"
note "earlier and the driver re-applies the exact window. That is src/engine/providers/archive-graph.ts."
DEFAULT_FROM="$(date -u +%Y-%m-%dT00:00:00Z)"
DEFAULT_TO="$(date -u -v+1d +%Y-%m-%dT00:00:00Z 2>/dev/null || date -u -d 'tomorrow' +%Y-%m-%dT00:00:00Z)"
say "Today's seeding is covered by ${DEFAULT_FROM} → ${DEFAULT_TO}."
ask MIGMATE_ARCHIVE_WINDOW_FROM "Window from (UTC, e.g. $DEFAULT_FROM):"
if [[ -z "$MIGMATE_ARCHIVE_WINDOW_FROM" ]]; then MIGMATE_ARCHIVE_WINDOW_FROM="$DEFAULT_FROM"; fi
ask MIGMATE_ARCHIVE_WINDOW_TO "Window to (UTC, exclusive, e.g. $DEFAULT_TO):"
if [[ -z "$MIGMATE_ARCHIVE_WINDOW_TO" ]]; then MIGMATE_ARCHIVE_WINDOW_TO="$DEFAULT_TO"; fi
write_env MIGMATE_ARCHIVE_WINDOW_FROM "$MIGMATE_ARCHIVE_WINDOW_FROM"
write_env MIGMATE_ARCHIVE_WINDOW_TO "$MIGMATE_ARCHIVE_WINDOW_TO"
say ""
say "Package partitions always stay UTC. The timezone is the one approved zone rendered alongside them."
ask MIGMATE_ARCHIVE_TIMEZONE "Display timezone (IANA, e.g. Europe/Stockholm):"
if [[ -z "$MIGMATE_ARCHIVE_TIMEZONE" ]]; then MIGMATE_ARCHIVE_TIMEZONE="Europe/Stockholm"; fi
write_env MIGMATE_ARCHIVE_TIMEZONE "$MIGMATE_ARCHIVE_TIMEZONE"
pause

stage "Prove the app and the samples against the tenant"
say "Nothing so far is evidence. This step authenticates the app, resolves the scope, follows both export"
say "routes to exhaustion and fetches real hosted-content bytes, so a missing prerequisite fails here"
say "rather than eleven minutes into a qualification run."
say ""
say "It will ask for the client secret once, store it 0600 under $PREREQ_DIR/entra, and never echo it."
if ! node "$(dirname "$0")/probe-archive-app.ts" --env "$ENV_FILE" --client-id "$MIGMATE_ARCHIVE_CLIENT_ID"; then
  warn "the prerequisites are not in place yet; fix what it named and re-run this wizard"
  exit 1
fi
pause

fi

stage "Operator job config and live probe config"
load_env MIGMATE_PREREQ_DIR MIGMATE_TENANT_ID MIGMATE_ARCHIVE_CLIENT_ID MIGMATE_ARCHIVE_SECRET_FILE \
  MIGMATE_ARCHIVE_TEAM_ID MIGMATE_ARCHIVE_CHANNEL_ID MIGMATE_ARCHIVE_USER_ID \
  MIGMATE_ARCHIVE_WINDOW_FROM MIGMATE_ARCHIVE_WINDOW_TO MIGMATE_ARCHIVE_TIMEZONE
PREREQ_DIR="$MIGMATE_PREREQ_DIR"
for required in MIGMATE_TENANT_ID MIGMATE_ARCHIVE_CLIENT_ID MIGMATE_ARCHIVE_SECRET_FILE \
  MIGMATE_ARCHIVE_TEAM_ID MIGMATE_ARCHIVE_CHANNEL_ID MIGMATE_ARCHIVE_USER_ID \
  MIGMATE_ARCHIVE_WINDOW_FROM MIGMATE_ARCHIVE_WINDOW_TO MIGMATE_ARCHIVE_TIMEZONE; do
  if [[ -z "${!required}" ]]; then
    warn "$required is missing from $ENV_FILE; run the wizard without --resume"
    exit 1
  fi
done

say "Two files, both outside the repository, both references only:"
note "  job.toml          what 'migmate init --type teams_archive --config' parses"
note "  probe-config.json what 'npm run qualify:route' parses"
ask MIGMATE_ARCHIVE_JOB_CONFIG "Job config path outside the repo (job-archive.toml):"
if [[ -z "$MIGMATE_ARCHIVE_JOB_CONFIG" ]]; then
  MIGMATE_ARCHIVE_JOB_CONFIG="$PREREQ_DIR/job-archive.toml"
fi
case "$MIGMATE_ARCHIVE_JOB_CONFIG" in
  /*) ;;
  *) warn "the path must be absolute"; exit 1 ;;
esac
case "$MIGMATE_ARCHIVE_JOB_CONFIG" in
  "$PWD"|"$PWD"/*) warn "keep the job config outside the repository"; exit 1 ;;
esac

cat > "$MIGMATE_ARCHIVE_JOB_CONFIG" <<TOML
# Migmate Teams archive job. References only; no secret values live here.
route = "teams_global_archive"
guarantees = "default"
cloud = "Global"
timezone = "$MIGMATE_ARCHIVE_TIMEZONE"
retainedHistory = false
transcripts = false
attachmentBytes = false

[window]
from = "$MIGMATE_ARCHIVE_WINDOW_FROM"
to = "$MIGMATE_ARCHIVE_WINDOW_TO"

[[scopes]]
kind = "channel"
teamId = "$MIGMATE_ARCHIVE_TEAM_ID"
channelId = "$MIGMATE_ARCHIVE_CHANNEL_ID"

[[scopes]]
kind = "user-chats"
userId = "$MIGMATE_ARCHIVE_USER_ID"

[graph]
tenantId = "$MIGMATE_TENANT_ID"
clientId = "$MIGMATE_ARCHIVE_CLIENT_ID"

[secrets.teams_graph_client_secret]
resolver = "file"
path = "$MIGMATE_ARCHIVE_SECRET_FILE"
mode = "0600"
TOML
chmod 600 "$MIGMATE_ARCHIVE_JOB_CONFIG"
write_env MIGMATE_ARCHIVE_JOB_CONFIG "$MIGMATE_ARCHIVE_JOB_CONFIG"
say "Onboard it with: migmate init --type teams_archive --config $MIGMATE_ARCHIVE_JOB_CONFIG"
say ""

ask MIGMATE_ARCHIVE_PROBE_CONFIG "Probe config path outside the repo (probe-config-archive.json):"
if [[ -z "$MIGMATE_ARCHIVE_PROBE_CONFIG" ]]; then
  MIGMATE_ARCHIVE_PROBE_CONFIG="$PREREQ_DIR/probe-config-archive.json"
fi
case "$MIGMATE_ARCHIVE_PROBE_CONFIG" in
  /*) ;;
  *) warn "the path must be absolute"; exit 1 ;;
esac
case "$MIGMATE_ARCHIVE_PROBE_CONFIG" in
  "$PWD"|"$PWD"/*) warn "keep the probe config outside the repository"; exit 1 ;;
esac

cat > "$MIGMATE_ARCHIVE_PROBE_CONFIG" <<JSON
{
  "schemaVersion": 1,
  "jobType": "teams_archive",
  "acknowledgement": "I authorize disposable live qualification probes",
  "jobConfig": {
    "guarantees": "default",
    "cloud": "Global",
    "timezone": "$MIGMATE_ARCHIVE_TIMEZONE",
    "retainedHistory": false,
    "transcripts": false,
    "attachmentBytes": false,
    "window": {
      "from": "$MIGMATE_ARCHIVE_WINDOW_FROM",
      "to": "$MIGMATE_ARCHIVE_WINDOW_TO"
    },
    "scopes": [
      {
        "kind": "channel",
        "teamId": "$MIGMATE_ARCHIVE_TEAM_ID",
        "channelId": "$MIGMATE_ARCHIVE_CHANNEL_ID"
      },
      { "kind": "user-chats", "userId": "$MIGMATE_ARCHIVE_USER_ID" }
    ],
    "graph": {
      "tenantId": "$MIGMATE_TENANT_ID",
      "clientId": "$MIGMATE_ARCHIVE_CLIENT_ID"
    },
    "secrets": {
      "teams_graph_client_secret": {
        "resolver": "file",
        "path": "$MIGMATE_ARCHIVE_SECRET_FILE",
        "mode": "0600"
      }
    }
  }
}
JSON
chmod 600 "$MIGMATE_ARCHIVE_PROBE_CONFIG"
write_env MIGMATE_ARCHIVE_PROBE_CONFIG "$MIGMATE_ARCHIVE_PROBE_CONFIG"
say "Qualify with: npm run qualify:route -- --config $MIGMATE_ARCHIVE_PROBE_CONFIG --output <new-directory>"
note "The archive route has no fixtures block: it mutates nothing and reads only the samples proved above."

finish
