#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

umask 077
ENV_FILE="${TMPDIR:-/tmp}/migmate-stage1-prereqs.env"

# --resume <env-file> skips every browser stage and re-runs only the config
# stages, for an operator whose earlier run already captured the values.
RESUME=0
if [[ "${1:-}" == "--resume" ]]; then
  RESUME=1
  ENV_FILE="${2:-}"
  if [[ ! -f "$ENV_FILE" ]]; then
    warn "usage: ${0##*/} --resume /path/to/.stage1-prereqs.env"
    exit 1
  fi
  set -a
  . "$ENV_FILE"
  set +a
  PREREQ_DIR="${MIGMATE_PREREQ_DIR:?the env file must record MIGMATE_PREREQ_DIR}"
  _STAGE_INDEX=6
fi

if (( ! RESUME )); then

banner "Migmate stage 1 prerequisites"

stage "Microsoft Entra app registration"
say "Official docs: register a single-tenant app, add the Microsoft Graph application permission Sites.Selected, then create one client secret."
open_url "https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app"
open_url "https://learn.microsoft.com/en-us/entra/identity-platform/how-to-add-credentials"
open_url "https://learn.microsoft.com/en-us/graph/permissions-reference"
open_url "https://entra.microsoft.com"
if ! confirm "Create the Entra app registration and client secret now?"; then
  warn "stopped before app registration."
  exit 1
fi
ask MIGMATE_PREREQ_DIR "Choose an operator-owned absolute directory outside the repo for these prerequisite files:"
case "$MIGMATE_PREREQ_DIR" in
  /*) ;;
  *) warn "Use an absolute path outside the repo."; exit 1 ;;
esac
case "$MIGMATE_PREREQ_DIR" in
  "$PWD"|"$PWD"/*)
    warn "Pick a path outside the repo."
    exit 1
    ;;
esac
PREREQ_DIR="$MIGMATE_PREREQ_DIR"
ENV_FILE="$PREREQ_DIR/.stage1-prereqs.env"
mkdir -p "$PREREQ_DIR/entra"
write_env MIGMATE_PREREQ_DIR "$PREREQ_DIR"
write_env MIGMATE_PREREQ_ENV_FILE "$ENV_FILE"
say "Create the app as Migmate in Entra ID > App registrations > New registration."
step "Use a single-tenant account type. Under Microsoft Graph application permissions, add Sites.Selected only; do not add tenant-wide Files.Read.All or Sites.Read.All."
ask MIGMATE_TENANT_ID "Paste the Directory (tenant) ID:"
ask MIGMATE_CLIENT_ID "Paste the Application (client) ID:"
MIGMATE_ENTRA_TENANT_ID_FILE="$PREREQ_DIR/entra/tenant-id.txt"
MIGMATE_ENTRA_CLIENT_ID_FILE="$PREREQ_DIR/entra/client-id.txt"
printf '%s\n' "$MIGMATE_TENANT_ID" > "$MIGMATE_ENTRA_TENANT_ID_FILE"
printf '%s\n' "$MIGMATE_CLIENT_ID" > "$MIGMATE_ENTRA_CLIENT_ID_FILE"
chmod 600 "$MIGMATE_ENTRA_TENANT_ID_FILE" "$MIGMATE_ENTRA_CLIENT_ID_FILE"
write_env MIGMATE_TENANT_ID "$MIGMATE_TENANT_ID"
write_env MIGMATE_CLIENT_ID "$MIGMATE_CLIENT_ID"
write_env MIGMATE_ENTRA_TENANT_ID_FILE "$MIGMATE_ENTRA_TENANT_ID_FILE"
write_env MIGMATE_ENTRA_CLIENT_ID_FILE "$MIGMATE_ENTRA_CLIENT_ID_FILE"
step "Go to Certificates & secrets > Client secrets > New client secret, then copy the Value once."
if ! confirm "Paste the client secret Value now?"; then
  warn "stopped before secret capture."
  exit 1
fi
ask_secret MIGMATE_CLIENT_SECRET "Paste the client secret Value:"
MIGMATE_ENTRA_CLIENT_SECRET_FILE="$PREREQ_DIR/entra/client-secret.txt"
printf '%s' "$MIGMATE_CLIENT_SECRET" > "$MIGMATE_ENTRA_CLIENT_SECRET_FILE"
chmod 600 "$MIGMATE_ENTRA_CLIENT_SECRET_FILE"
write_env MIGMATE_ENTRA_CLIENT_SECRET_FILE "$MIGMATE_ENTRA_CLIENT_SECRET_FILE"
say "Keep the secret file outside the repo. The job config will reference the file, not the secret text."

stage "SharePoint source identifiers"
say "The official docs confirm the Graph GET endpoints; they do not give a single portal click path. Use Graph Explorer or another Graph client to fetch the ids."
open_url "https://learn.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0"
open_url "https://learn.microsoft.com/en-us/graph/api/drive-get?view=graph-rest-1.0"
open_url "https://learn.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0"
open_url "https://developer.microsoft.com/graph/graph-explorer"
if ! confirm "Look up the source site id, document-library drive id, and mapping-root item id now?"; then
  warn "stopped before source ids."
  exit 1
fi
say "Use these requests as the source of truth:"
note "GET /sites/{hostname}:/sites/{server-relative-path}"
note "GET /sites/{site-id}/drive"
note "GET /sites/{site-id}/drive/root"
ask MIGMATE_SOURCE_SITE_ID "Paste the SharePoint site id:"
ask MIGMATE_SOURCE_DRIVE_ID "Paste the document-library drive id:"
ask MIGMATE_MAPPING_ROOT_ITEM_ID "Paste the stable mapping-root item id:"
mkdir -p "$PREREQ_DIR/sharepoint"
MIGMATE_SOURCE_SITE_ID_FILE="$PREREQ_DIR/sharepoint/site-id.txt"
MIGMATE_SOURCE_DRIVE_ID_FILE="$PREREQ_DIR/sharepoint/drive-id.txt"
MIGMATE_MAPPING_ROOT_ITEM_ID_FILE="$PREREQ_DIR/sharepoint/mapping-root-item-id.txt"
printf '%s\n' "$MIGMATE_SOURCE_SITE_ID" > "$MIGMATE_SOURCE_SITE_ID_FILE"
printf '%s\n' "$MIGMATE_SOURCE_DRIVE_ID" > "$MIGMATE_SOURCE_DRIVE_ID_FILE"
printf '%s\n' "$MIGMATE_MAPPING_ROOT_ITEM_ID" > "$MIGMATE_MAPPING_ROOT_ITEM_ID_FILE"
chmod 600 "$MIGMATE_SOURCE_SITE_ID_FILE" "$MIGMATE_SOURCE_DRIVE_ID_FILE" "$MIGMATE_MAPPING_ROOT_ITEM_ID_FILE"
write_env MIGMATE_SOURCE_SITE_ID "$MIGMATE_SOURCE_SITE_ID"
write_env MIGMATE_SOURCE_DRIVE_ID "$MIGMATE_SOURCE_DRIVE_ID"
write_env MIGMATE_MAPPING_ROOT_ITEM_ID "$MIGMATE_MAPPING_ROOT_ITEM_ID"
write_env MIGMATE_SOURCE_SITE_ID_FILE "$MIGMATE_SOURCE_SITE_ID_FILE"
write_env MIGMATE_SOURCE_DRIVE_ID_FILE "$MIGMATE_SOURCE_DRIVE_ID_FILE"
write_env MIGMATE_MAPPING_ROOT_ITEM_ID_FILE "$MIGMATE_MAPPING_ROOT_ITEM_ID_FILE"
say "This stage is only for a SharePoint document-library source. My Drive is out of scope."

stage "Admin consent and site grant"
say "Microsoft docs confirm tenant-wide admin consent from Entra App registrations and the site permission API; the site grant itself is a Graph POST."
open_url "https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/grant-admin-consent"
open_url "https://learn.microsoft.com/en-us/graph/permissions-selected-overview?view=graph-rest-1.0"
open_url "https://learn.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0"
open_url "https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/manage-application-permissions"
open_url "https://entra.microsoft.com"
note "Do not add a redirect URI just for consent; this client-credentials app does not need one."
if ! confirm "Grant tenant-wide admin consent and the exact source-site read grant now?"; then
  warn "stopped before consent and site grant."
  exit 1
fi
step "In Entra ID > App registrations > All applications, open the app whose Application ID is ${MIGMATE_CLIENT_ID}, then select API permissions. Confirm Sites.Selected is the only Graph application permission, remove Files.Read.All if present, and select Grant admin consent."
step "In Graph Explorer, consent its delegated Sites.FullControl.All permission while signed in as SharePoint Administrator or higher."
step "In Graph Explorer, select POST and put only https://graph.microsoft.com/v1.0/sites/${MIGMATE_SOURCE_SITE_ID}/permissions in the query bar."
step "Under Request Headers, add Content-Type with value application/json. Under Request Body, paste the JSON shown next; require HTTP 201."
note "{\"roles\":[\"read\"],\"grantedToIdentities\":[{\"application\":{\"id\":\"${MIGMATE_CLIENT_ID}\",\"displayName\":\"Migmate\"}}]}"
step "After the 201 response, reopen Graph Explorer's permissions panel, search Sites.FullControl.All, and select Unconsent. If unavailable, revoke it in Entra ID > Enterprise apps > Graph Explorer > Permissions."
pause "Press Enter once the consent and site grant are complete."

stage "Google service account and Shared Drive share"
say "Google docs confirm service-account creation, JSON key creation, Shared Drive member roles, and limited-access folder sharing. They do not confirm one universal folder-share click path for a service account, so stop if your UI differs rather than guessing."
open_url "https://docs.cloud.google.com/iam/docs/service-accounts-create?hl=en"
open_url "https://docs.cloud.google.com/iam/docs/keys-create-delete?hl=en"
open_url "https://support.google.com/a/users/answer/9310249?hl=en"
open_url "https://support.google.com/drive/answer/7286514?co=GENIE.Platform%3DDesktop&hl=en"
open_url "https://support.google.com/drive/answer/14254362?co=GENIE.Platform%3DDesktop&hl=en"
open_url "https://drive.google.com"
if ! confirm "Create the service account, create its JSON key, and share the destination folder now?"; then
  warn "stopped before Google prerequisites."
  exit 1
fi
say "Create the service account in Google Cloud Console, then paste the service-account email address."
ask MIGMATE_GOOGLE_SERVICE_ACCOUNT_EMAIL "Paste the service-account email:"
mkdir -p "$PREREQ_DIR/google"
MIGMATE_GOOGLE_SERVICE_ACCOUNT_EMAIL_FILE="$PREREQ_DIR/google/service-account-email.txt"
printf '%s\n' "$MIGMATE_GOOGLE_SERVICE_ACCOUNT_EMAIL" > "$MIGMATE_GOOGLE_SERVICE_ACCOUNT_EMAIL_FILE"
chmod 600 "$MIGMATE_GOOGLE_SERVICE_ACCOUNT_EMAIL_FILE"
write_env MIGMATE_GOOGLE_SERVICE_ACCOUNT_EMAIL "$MIGMATE_GOOGLE_SERVICE_ACCOUNT_EMAIL"
write_env MIGMATE_GOOGLE_SERVICE_ACCOUNT_EMAIL_FILE "$MIGMATE_GOOGLE_SERVICE_ACCOUNT_EMAIL_FILE"
MIGMATE_GOOGLE_SERVICE_ACCOUNT_KEY_FILE="$PREREQ_DIR/google/service-account-key.json"
if command -v gcloud >/dev/null 2>&1; then
  if gcloud iam service-accounts keys create "$MIGMATE_GOOGLE_SERVICE_ACCOUNT_KEY_FILE" --iam-account="$MIGMATE_GOOGLE_SERVICE_ACCOUNT_EMAIL"; then
    chmod 600 "$MIGMATE_GOOGLE_SERVICE_ACCOUNT_KEY_FILE"
    say "gcloud created the JSON key file directly."
  else
    warn "gcloud could not create the key; download it from the console and save it to $MIGMATE_GOOGLE_SERVICE_ACCOUNT_KEY_FILE."
    pause "Press Enter once the JSON key is in place."
  fi
else
  warn "gcloud is not installed; download the JSON key from the console and save it to $MIGMATE_GOOGLE_SERVICE_ACCOUNT_KEY_FILE."
  pause "Press Enter once the JSON key is in place."
fi
chmod 600 "$MIGMATE_GOOGLE_SERVICE_ACCOUNT_KEY_FILE"
write_env MIGMATE_GOOGLE_SERVICE_ACCOUNT_KEY_FILE "$MIGMATE_GOOGLE_SERVICE_ACCOUNT_KEY_FILE"
say "Optional file-job impersonation: set top-level impersonate = true and subject = \"files@example.com\" in job TOML before any table header. Otherwise the service account acts as itself."
say "For impersonation, a Workspace admin must authorize domain-wide delegation for the service account's numeric client id (JSON client_id, not its email), with ONLY https://www.googleapis.com/auth/drive. Choose an ordinary non-admin subject and share the destination with that subject instead. Migmate cannot check admin status without Admin SDK scopes and never requests them."
say "Delegation is a domain-wide key. Preflight proves token issuance and about.user.emailAddress equals the subject. Plan and report show the acting account; after the job, delete the service-account key and delegation entry listed as open report items. Keep impersonate out of rclone.conf: Migmate injects it per mapping; operator overrides refuse. This does not enable drive creation."
step "Share the destination Shared Drive folder as Content manager with the acting account: the service-account email by default, or the configured subject when impersonating."
step "Capture the destination Shared Drive id and the destination folder id. The folder id is the last path segment in the folder URL. If your UI does not surface the Shared Drive id clearly, do not guess."
if ! confirm "The destination is a Shared Drive folder, not My Drive?"; then
  warn "My Drive is out of scope for stage 1."
  exit 1
fi
ask MIGMATE_SHARED_DRIVE_ID "Paste the destination Shared Drive id:"
ask MIGMATE_DESTINATION_FOLDER_ID "Paste the destination folder id:"
MIGMATE_SHARED_DRIVE_ID_FILE="$PREREQ_DIR/google/shared-drive-id.txt"
MIGMATE_DESTINATION_FOLDER_ID_FILE="$PREREQ_DIR/google/destination-folder-id.txt"
printf '%s\n' "$MIGMATE_SHARED_DRIVE_ID" > "$MIGMATE_SHARED_DRIVE_ID_FILE"
printf '%s\n' "$MIGMATE_DESTINATION_FOLDER_ID" > "$MIGMATE_DESTINATION_FOLDER_ID_FILE"
chmod 600 "$MIGMATE_SHARED_DRIVE_ID_FILE" "$MIGMATE_DESTINATION_FOLDER_ID_FILE"
write_env MIGMATE_SHARED_DRIVE_ID "$MIGMATE_SHARED_DRIVE_ID"
write_env MIGMATE_DESTINATION_FOLDER_ID "$MIGMATE_DESTINATION_FOLDER_ID"
write_env MIGMATE_SHARED_DRIVE_ID_FILE "$MIGMATE_SHARED_DRIVE_ID_FILE"
write_env MIGMATE_DESTINATION_FOLDER_ID_FILE "$MIGMATE_DESTINATION_FOLDER_ID_FILE"
pause "Press Enter once the folder share is complete."

stage "rclone.conf"
say "Migmate runs sequential rclone copy passes using these two remotes with per-mapping connection overrides. SharePoint is addressed by path within a drive pinned by id, never root_folder_id. Copies preserve supported timestamps and empty folders, with owner, permission and label metadata off."
open_url "https://rclone.org/onedrive/"
open_url "https://rclone.org/drive/"
if ! confirm "Write the operator-owned rclone.conf now?"; then
  warn "stopped before rclone.conf."
  exit 1
fi
mkdir -p "$PREREQ_DIR/rclone"
MIGMATE_RCLONE_CONF_FILE="$PREREQ_DIR/rclone/rclone.conf"
MIGMATE_RCLONE_CLIENT_SECRET=$(<"$MIGMATE_ENTRA_CLIENT_SECRET_FILE")
cat > "$MIGMATE_RCLONE_CONF_FILE" <<EOF
[sharepoint-source]
type = onedrive
client_id = $MIGMATE_CLIENT_ID
client_secret = $MIGMATE_RCLONE_CLIENT_SECRET
client_credentials = true
tenant = $MIGMATE_TENANT_ID
drive_type = documentLibrary
drive_id = $MIGMATE_SOURCE_DRIVE_ID
root_folder_id = $MIGMATE_MAPPING_ROOT_ITEM_ID

[google-destination]
type = drive
scope = drive
service_account_file = $MIGMATE_GOOGLE_SERVICE_ACCOUNT_KEY_FILE
team_drive = $MIGMATE_SHARED_DRIVE_ID
root_folder_id = $MIGMATE_DESTINATION_FOLDER_ID
EOF
chmod 600 "$MIGMATE_RCLONE_CONF_FILE"
write_env MIGMATE_RCLONE_CONF_FILE "$MIGMATE_RCLONE_CONF_FILE"
say "Do not move this config into the repo; Migmate will read it only by path."

stage "Vendored rclone v1.75.0"
say "The downloads page publishes SHA256SUMS for the exact v1.75.0 archive. This stage downloads the matching archive for this OS/arch, checks the checksum, extracts the binary, and refuses any other version."
open_url "https://downloads.rclone.org/v1.75.0/"
if ! confirm "Download and verify vendored rclone now?"; then
  warn "stopped before vendoring rclone."
  exit 1
fi
os_name=$(uname -s)
arch_name=$(uname -m)
case "$os_name" in
  Darwin) os_arch_prefix="osx" ;;
  Linux) os_arch_prefix="linux" ;;
  MINGW*|MSYS*|CYGWIN*)
    warn "Windows is not a supported platform; see docs/adr/0002-drop-windows.md"
    exit 1
    ;;
  *)
    warn "unsupported OS for the vendored rclone archive: $os_name"
    exit 1
    ;;
esac
case "$arch_name" in
  arm64|aarch64) os_arch_suffix="arm64" ;;
  x86_64|amd64) os_arch_suffix="amd64" ;;
  armv7l|armv7) os_arch_suffix="arm-v7" ;;
  armv6l|armv6) os_arch_suffix="arm-v6" ;;
  *)
    warn "unsupported architecture for the vendored rclone archive: $arch_name"
    exit 1
    ;;
esac
platform="$os_arch_prefix-$os_arch_suffix"
RCLONE_VENDOR_DIR="$PWD/vendor/rclone/$platform"
mkdir -p "$RCLONE_VENDOR_DIR"
archive_name="rclone-v1.75.0-$platform.zip"
archive_file="$RCLONE_VENDOR_DIR/$archive_name"
checksum_file="$RCLONE_VENDOR_DIR/SHA256SUMS"
curl -fsSL "https://downloads.rclone.org/v1.75.0/$archive_name" -o "$archive_file"
curl -fsSL "https://downloads.rclone.org/v1.75.0/SHA256SUMS" -o "$checksum_file"
expected_sha=$(awk -v file="$archive_name" '$2 == file { print $1; exit }' "$checksum_file")
if command -v sha256sum >/dev/null 2>&1; then
  actual_sha=$(sha256sum "$archive_file" | awk '{ print $1 }')
else
  actual_sha=$(shasum -a 256 "$archive_file" | awk '{ print $1 }')
fi
if [[ -z "$expected_sha" ]]; then
  warn "could not find the expected checksum for $archive_name"
  exit 1
fi
if [[ "$actual_sha" != "$expected_sha" ]]; then
  warn "checksum mismatch for $archive_name"
  warn "expected $expected_sha"
  warn "actual   $actual_sha"
  exit 1
fi
digest_file="$RCLONE_VENDOR_DIR/rclone-v1.75.0.sha256"
printf '%s  %s\n' "$actual_sha" "$archive_name" > "$digest_file"
tmp_extract=$(mktemp -d)
unzip -q "$archive_file" -d "$tmp_extract"
rclone_source_bin=$(find "$tmp_extract" -type f -name rclone -print -quit)
if [[ -z "$rclone_source_bin" ]]; then
  warn "could not locate the rclone binary inside $archive_name"
  exit 1
fi
RCLONE_BINARY_FILE="$RCLONE_VENDOR_DIR/rclone"
install -m 755 "$rclone_source_bin" "$RCLONE_BINARY_FILE"
version_json=$("$RCLONE_BINARY_FILE" rc --loopback core/version)
rclone_version=$(printf '%s' "$version_json" | tr -d '\n' | sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
rclone_version=${rclone_version#v}
if [[ "$rclone_version" != "1.75.0" ]]; then
  warn "rclone version must be exactly 1.75.0; got ${rclone_version:-unknown}"
  exit 1
fi
write_env MIGMATE_RCLONE_PLATFORM "$platform"
write_env MIGMATE_RCLONE_ARCHIVE_FILE "$archive_file"
write_env MIGMATE_RCLONE_CHECKSUM_FILE "$checksum_file"
write_env MIGMATE_RCLONE_BINARY_FILE "$RCLONE_BINARY_FILE"
write_env MIGMATE_RCLONE_SHA256_FILE "$digest_file"
say "Vendored rclone version verified: 1.75.0"
fi

stage "Operator job config"
say "This is the config migmate init --config reads. It stores typed file-backed references, never secret values. Existing mappings run sequentially into existing destinations; there is no manifest loader or mapping-concurrency setting."
say "Use dedicated destination roots: rclone copy never deletes, but can update same-path content without collision protection. Status records mapping passes and errors; execute retries failed/interrupted passes and skips completed ones. Ctrl-C stops cooperatively with exit 130. JSONL streams mapping stats; verify hashes files separately."
if ! confirm "Write the operator job config now?"; then
  warn "stopped before the job config."
  exit 1
fi
ask MIGMATE_JOB_CONFIG "Choose the job config path outside the repo (job.toml):"
case "$MIGMATE_JOB_CONFIG" in
  /*) ;;
  *) warn "Use an absolute path outside the repo."; exit 1 ;;
esac
case "$MIGMATE_JOB_CONFIG" in
  "$PWD"|"$PWD"/*) warn "Pick a path outside the repo."; exit 1 ;;
esac
ask MIGMATE_MAPPING_ID "Name this mapping (letters, digits, _!.,@- only):"
# No {n,m} interval: BSD regcomp caps repetition at RE_DUP_MAX, so a 512 bound
# fails to compile and would reject every id.
if [[ -z "$MIGMATE_MAPPING_ID" || ${#MIGMATE_MAPPING_ID} -gt 512 ]] ||
  [[ "$MIGMATE_MAPPING_ID" =~ [^A-Za-z0-9_!.,@-] ]]; then
  warn "mapping id must be 1-512 characters from A-Za-z0-9_!.,@-"
  exit 1
fi
mkdir -p "$(dirname "$MIGMATE_JOB_CONFIG")"
cat > "$MIGMATE_JOB_CONFIG" <<EOF
# Migmate file migration job. References only; no secret values live here.
route = "sharepoint_library_to_shared_drive"

[[mappings]]
id = "$MIGMATE_MAPPING_ID"
sourceSiteId = "$MIGMATE_SOURCE_SITE_ID"
sourceDriveId = "$MIGMATE_SOURCE_DRIVE_ID"
sourceItemId = "$MIGMATE_MAPPING_ROOT_ITEM_ID"
destDriveId = "$MIGMATE_SHARED_DRIVE_ID"
destFolderId = "$MIGMATE_DESTINATION_FOLDER_ID"

[options]

[rclone]
sourceRemote = "sharepoint-source"
destinationRemote = "google-destination"
config = { resolver = "file", path = "$MIGMATE_RCLONE_CONF_FILE", mode = "0600" }
EOF
chmod 600 "$MIGMATE_JOB_CONFIG"
write_env MIGMATE_JOB_CONFIG "$MIGMATE_JOB_CONFIG"
write_env MIGMATE_MAPPING_ID "$MIGMATE_MAPPING_ID"
note "Onboard it with: migmate init --type file_migration --config $MIGMATE_JOB_CONFIG"

stage "Optional reverse direction: Google Shared Drives to SharePoint"
say "Reverse jobs copy Google Shared Drive folders into existing SharePoint libraries or folders. SharePoint is written only by a separate destination app whose Graph application permissions are exactly Sites.ReadWrite.All; the read-only source app above never gains a write role, and preflight refuses anything else with credential_permissions_invalid."
say "The reverse job gets its own rclone.conf and job.toml, so forward jobs never hold the write credential. Sources are read as the acting Google account; Migmate never adds it to a source drive."
open_url "https://learn.microsoft.com/en-us/graph/permissions-reference#sitesreadwriteall"
if confirm "Set up a SharePoint destination app and reverse job config now?"; then
  step "In Entra ID > App registrations > New registration, create a second single-tenant app (for example Migmate SharePoint writer)."
  step "Under API permissions add only the Microsoft Graph application permission Sites.ReadWrite.All, select Grant admin consent, then create one client secret and copy its Value."
  ask MIGMATE_SP_DEST_CLIENT_ID "Paste the destination app's Application (client) ID:"
  if [[ "$MIGMATE_SP_DEST_CLIENT_ID" == "$MIGMATE_CLIENT_ID" ]]; then
    warn "the destination app must be a different app from the read-only source app."
    exit 1
  fi
  mkdir -p "$PREREQ_DIR/entra" "$PREREQ_DIR/rclone"
  MIGMATE_SP_DEST_SECRET_FILE="${MIGMATE_SP_DEST_SECRET_FILE:-$PREREQ_DIR/entra/sharepoint-destination-client-secret.txt}"
  if [[ -s "$MIGMATE_SP_DEST_SECRET_FILE" ]]; then
    say "Reusing the client secret already stored at $MIGMATE_SP_DEST_SECRET_FILE."
  else
    ask_secret MIGMATE_SP_DEST_SECRET "Paste the destination app's client secret Value:"
    if [[ -z "$MIGMATE_SP_DEST_SECRET" ]]; then
      warn "no client secret was supplied."
      exit 1
    fi
    printf '%s' "$MIGMATE_SP_DEST_SECRET" > "$MIGMATE_SP_DEST_SECRET_FILE"
    unset MIGMATE_SP_DEST_SECRET
  fi
  chmod 600 "$MIGMATE_SP_DEST_SECRET_FILE"
  note "Fetch a destination library's drive id with GET /sites/{site-id}/drives. Every mapping overrides it; the remote only needs a valid seed."
  ask MIGMATE_SP_DEST_DRIVE_ID "Paste one destination document-library drive id:"
  step "Add the acting Google account (the impersonation subject, or the service account when impersonation is off) as a member of every source Shared Drive. Preflight names each source drive it cannot read."
  ask MIGMATE_REVERSE_SOURCE_DRIVE_ID "Paste one source Shared Drive id (seed only; every mapping overrides it):"
  MIGMATE_REVERSE_RCLONE_CONF_FILE="$PREREQ_DIR/rclone/reverse-rclone.conf"
  MIGMATE_SP_DEST_CLIENT_SECRET=$(<"$MIGMATE_SP_DEST_SECRET_FILE")
  cat > "$MIGMATE_REVERSE_RCLONE_CONF_FILE" <<EOF
[google-drive]
type = drive
scope = drive
service_account_file = $MIGMATE_GOOGLE_SERVICE_ACCOUNT_KEY_FILE
team_drive = $MIGMATE_REVERSE_SOURCE_DRIVE_ID
root_folder_id = $MIGMATE_REVERSE_SOURCE_DRIVE_ID

[sharepoint-destination]
type = onedrive
client_id = $MIGMATE_SP_DEST_CLIENT_ID
client_secret = $MIGMATE_SP_DEST_CLIENT_SECRET
client_credentials = true
tenant = $MIGMATE_TENANT_ID
drive_type = documentLibrary
drive_id = $MIGMATE_SP_DEST_DRIVE_ID
EOF
  unset MIGMATE_SP_DEST_CLIENT_SECRET
  chmod 600 "$MIGMATE_REVERSE_RCLONE_CONF_FILE"
  ask MIGMATE_REVERSE_JOB_CONFIG "Choose the reverse job config path outside the repo (reverse-job.toml):"
  case "$MIGMATE_REVERSE_JOB_CONFIG" in
    /*) ;;
    *) warn "Use an absolute path outside the repo."; exit 1 ;;
  esac
  case "$MIGMATE_REVERSE_JOB_CONFIG" in
    "$PWD"|"$PWD"/*) warn "Pick a path outside the repo."; exit 1 ;;
  esac
  mkdir -p "$(dirname "$MIGMATE_REVERSE_JOB_CONFIG")"
  cat > "$MIGMATE_REVERSE_JOB_CONFIG" <<EOF
# Migmate Google Shared Drive -> SharePoint job. References only; no secret values live here.
# Add top-level impersonate = true and subject = "files@example.com" here to act as that account.
# Mappings come from a manifest: migmate manifest load --job ID --file mappings.json

[options]

[rclone]
destinationRemote = "google-drive"
sharepointDestinationRemote = "sharepoint-destination"
config = { resolver = "file", path = "$MIGMATE_REVERSE_RCLONE_CONF_FILE", mode = "0600" }
EOF
  chmod 600 "$MIGMATE_REVERSE_JOB_CONFIG"
  write_env MIGMATE_SP_DEST_CLIENT_ID "$MIGMATE_SP_DEST_CLIENT_ID"
  write_env MIGMATE_SP_DEST_SECRET_FILE "$MIGMATE_SP_DEST_SECRET_FILE"
  write_env MIGMATE_SP_DEST_DRIVE_ID "$MIGMATE_SP_DEST_DRIVE_ID"
  write_env MIGMATE_REVERSE_SOURCE_DRIVE_ID "$MIGMATE_REVERSE_SOURCE_DRIVE_ID"
  write_env MIGMATE_REVERSE_RCLONE_CONF_FILE "$MIGMATE_REVERSE_RCLONE_CONF_FILE"
  write_env MIGMATE_REVERSE_JOB_CONFIG "$MIGMATE_REVERSE_JOB_CONFIG"
  note "Onboard it with: migmate init --type file_migration --config $MIGMATE_REVERSE_JOB_CONFIG, then load a manifest of google_shared_drive -> sharepoint mappings (README: Google Shared Drives to SharePoint)."
else
  note "Skipped the reverse direction; forward jobs do not need it."
fi

stage "Optional live test config"
say "The optional live test exercises the route with real operations, so it needs disposable roots it may create and delete inside, and a second same-tenant app that may write to the disposable source folder. The normal route credential stays read-only. Jobs do not need it."
open_url "https://learn.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0"
if ! confirm "Write the optional live test config now?"; then
  finish
  note "Skipped the optional live test config; the job config above is complete."
  exit 0
fi
say "Create a throwaway folder in the source library and a throwaway folder in the destination Shared Drive. The probe suite creates and deletes items beneath both, and deletes only ids it created itself."
step "Register the second app, then grant it the write role on the source site. This prints the exact request and proves the grant afterwards:"
note "  node scripts/probe-mutator-app.ts --env $ENV_FILE --client-id <app-id> --grant-instructions"
ask MIGMATE_PROBE_SOURCE_ITEM_ID "Paste the disposable source folder item id:"
ask MIGMATE_PROBE_DEST_FOLDER_ID "Paste the disposable destination folder id:"
ask MIGMATE_PROBE_MUTATOR_CLIENT_ID "Paste the second (source-write) app's Application (client) ID:"
if [[ "$MIGMATE_PROBE_MUTATOR_CLIENT_ID" == "$MIGMATE_CLIENT_ID" ]]; then
  warn "the probe mutator must be a different app from the read-only route app."
  exit 1
fi
mkdir -p "$PREREQ_DIR/entra"
MIGMATE_PROBE_MUTATOR_SECRET_FILE="${MIGMATE_PROBE_MUTATOR_SECRET_FILE:-$PREREQ_DIR/entra/probe-mutator-client-secret.txt}"
if [[ -s "$MIGMATE_PROBE_MUTATOR_SECRET_FILE" ]]; then
  say "Reusing the client secret already stored at $MIGMATE_PROBE_MUTATOR_SECRET_FILE."
else
  ask_secret MIGMATE_PROBE_MUTATOR_SECRET "Paste the second app's client secret value:"
  if [[ -z "$MIGMATE_PROBE_MUTATOR_SECRET" ]]; then
    warn "no client secret was supplied."
    exit 1
  fi
  printf '%s' "$MIGMATE_PROBE_MUTATOR_SECRET" > "$MIGMATE_PROBE_MUTATOR_SECRET_FILE"
  unset MIGMATE_PROBE_MUTATOR_SECRET
fi
chmod 600 "$MIGMATE_PROBE_MUTATOR_SECRET_FILE"
say "Capability samples are optional, read-only, and must be direct children of the disposable source root. Leave one empty when the tenant has no such item; the gate then records it as unavailable rather than claiming the observation."
ask MIGMATE_PROBE_PACKAGE_ID "Paste a package item id, e.g. a OneNote notebook (Enter to skip):"
ask MIGMATE_PROBE_REFERENCE_ID "Paste a reference (remoteItem) id (Enter to skip):"
ask MIGMATE_PROBE_UNDOWNLOADABLE_ID "Paste an undownloadable item id (Enter to skip):"
special_sources=""
for pair in "packageId:$MIGMATE_PROBE_PACKAGE_ID" \
  "referenceId:$MIGMATE_PROBE_REFERENCE_ID" \
  "undownloadableId:$MIGMATE_PROBE_UNDOWNLOADABLE_ID"; do
  key=${pair%%:*}
  value=${pair#*:}
  [[ -z "$value" ]] && continue
  special_sources+="$(printf '\n      "%s": "%s",' "$key" "$value")"
done
if [[ -n "$special_sources" ]]; then
  # Trailing comma removed: this is emitted into strict JSON.
  special_sources="$(printf ',\n    "specialSources": {%s\n    }' "${special_sources%,}")"
fi
write_env MIGMATE_PROBE_PACKAGE_ID "$MIGMATE_PROBE_PACKAGE_ID"
write_env MIGMATE_PROBE_REFERENCE_ID "$MIGMATE_PROBE_REFERENCE_ID"
write_env MIGMATE_PROBE_UNDOWNLOADABLE_ID "$MIGMATE_PROBE_UNDOWNLOADABLE_ID"
ask MIGMATE_PROBE_CONFIG "Choose the probe config path outside the repo (probe-config.json):"
case "$MIGMATE_PROBE_CONFIG" in
  /*) ;;
  *) warn "Use an absolute path outside the repo."; exit 1 ;;
esac
case "$MIGMATE_PROBE_CONFIG" in
  "$PWD"|"$PWD"/*) warn "Pick a path outside the repo."; exit 1 ;;
esac
mkdir -p "$(dirname "$MIGMATE_PROBE_CONFIG")"
cat > "$MIGMATE_PROBE_CONFIG" <<EOF
{
  "schemaVersion": 1,
  "jobType": "file_migration",
  "acknowledgement": "I authorize disposable live test probes",
  "jobConfig": {
    "rclone": {
      "config": { "resolver": "file", "path": "$MIGMATE_RCLONE_CONF_FILE", "mode": "0600" },
      "sourceRemote": "sharepoint-source",
      "destinationRemote": "google-destination"
    },
    "mappings": [
      {
        "id": "$MIGMATE_MAPPING_ID",
        "sourceSiteId": "$MIGMATE_SOURCE_SITE_ID",
        "sourceDriveId": "$MIGMATE_SOURCE_DRIVE_ID",
        "sourceItemId": "$MIGMATE_PROBE_SOURCE_ITEM_ID",
        "destDriveId": "$MIGMATE_SHARED_DRIVE_ID",
        "destFolderId": "$MIGMATE_PROBE_DEST_FOLDER_ID"
      }
    ]
  },
  "fixtures": {
    "disposableRoots": {
      "sourceDriveId": "$MIGMATE_SOURCE_DRIVE_ID",
      "sourceItemId": "$MIGMATE_PROBE_SOURCE_ITEM_ID",
      "destDriveId": "$MIGMATE_SHARED_DRIVE_ID",
      "destFolderId": "$MIGMATE_PROBE_DEST_FOLDER_ID",
      "acknowledged": true
    },
    "graphMutation": {
      "tenantId": "$MIGMATE_TENANT_ID",
      "clientId": "$MIGMATE_PROBE_MUTATOR_CLIENT_ID",
      "clientSecret": { "resolver": "file", "path": "$MIGMATE_PROBE_MUTATOR_SECRET_FILE", "mode": "0600" }
    }$special_sources
  }
}
EOF
chmod 600 "$MIGMATE_PROBE_CONFIG"
write_env MIGMATE_PROBE_CONFIG "$MIGMATE_PROBE_CONFIG"
write_env MIGMATE_PROBE_SOURCE_ITEM_ID "$MIGMATE_PROBE_SOURCE_ITEM_ID"
write_env MIGMATE_PROBE_DEST_FOLDER_ID "$MIGMATE_PROBE_DEST_FOLDER_ID"
write_env MIGMATE_PROBE_MUTATOR_CLIENT_ID "$MIGMATE_PROBE_MUTATOR_CLIENT_ID"
write_env MIGMATE_PROBE_MUTATOR_SECRET_FILE "$MIGMATE_PROBE_MUTATOR_SECRET_FILE"
note "Run the live test with: npm run test:live -- --config $MIGMATE_PROBE_CONFIG"
note "Secrets living outside the repo: $MIGMATE_ENTRA_CLIENT_SECRET_FILE, $MIGMATE_PROBE_MUTATOR_SECRET_FILE, $MIGMATE_GOOGLE_SERVICE_ACCOUNT_KEY_FILE, and $MIGMATE_RCLONE_CONF_FILE."
finish
